# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: FirstJob
    steps:
    - bash: echo build first job
  - job: SecondJob
    steps:
      - bash: echo second job
- stage: DevDeploy
  jobs:
  - job: DEVJob
    steps:
    - bash: echo build dev job
- stage: QAdeploy
  jobs:
  - job: QAJob
    steps:
    - bash: echo build qa job
- stage: PRODdeploy
  jobs:
  - job: PRODJob
    steps:
    - bash: echo build prod job
  